before_install:
  - git config --global user.name travis
  - git config --global user.email travis@locahost
  - "npm install npm@4 -g"
language: node_js
script:
  - npm install node-coverage-server -g
  - npm run lint
  - npm run coverage
  - cat coverage/lcov.info | node-coverage-cli --url https://node-coverage-server.herokuapp.com
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
os:
  - linux
sudo: false
